from processors.classification_processor import ClassificationProcessor
from processors.cifar10_classification_processor import Cifar10ClassificationProcessor
from processors.imagenet_classification_processor import ImageNetClassificationProcessor

from processors.anchor_box_processor import AnchorBoxProcessor
from processors.pascal_voc_anchor_box_processor import PascalVOCAnchorBoxProcessor

from processors.segmentation_processor import SegmentationProcessor
from processors.pascal_voc_segmentation_processor import PascalVOCSegmentationProcessor
from processors.bdd100k_segmentation_processor import BDD100KSegmentationProcessor