from processors.classification_processor import ClassificationProcessor
from processors.cifar10_classification_processor import Cifar10ClassificationProcessor
from processors.imagenet_classification_processor import ImageNetClassificationProcessor

from processors.anchor_box_processor import AnchorBoxProcessor